package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"gopkg.in/yaml.v3"
)

type frontMatter struct {
	Code     string `yaml:"code"`
	Category string `yaml:"category"`
	ExitCode int    `yaml:"exit_code"`
	Template string `yaml:"template"`
	Message  string `yaml:"message"`
}

type entry struct {
	Code      string
	ConstName string
	Category  string
	ExitCode  int
	Template  string
}

func main() {
	inputDir := flag.String("input", "", "Path to docs/errors directory")
	outputFile := flag.String("output", "", "Output Go file path")
	flag.Parse()

	if *inputDir == "" || *outputFile == "" {
		fmt.Fprintln(os.Stderr, "usage: gen-errors -input <docs/errors> -output <catalog_gen.go>")
		os.Exit(2)
	}

	entries, err := loadEntries(*inputDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "load entries: %v\n", err)
		os.Exit(1)
	}

	if err := writeCatalog(*outputFile, entries); err != nil {
		fmt.Fprintf(os.Stderr, "write catalog: %v\n", err)
		os.Exit(1)
	}
}

func loadEntries(inputDir string) ([]entry, error) {
	matches, err := filepath.Glob(filepath.Join(inputDir, "*.md"))
	if err != nil {
		return nil, fmt.Errorf("glob markdown files: %w", err)
	}

	entries := make([]entry, 0, len(matches))
	for _, path := range matches {
		data, err := os.ReadFile(path)
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", path, err)
		}

		fmText, ok := extractFrontMatter(string(data))
		if !ok {
			continue
		}

		var fm frontMatter
		if err := yaml.Unmarshal([]byte(fmText), &fm); err != nil {
			return nil, fmt.Errorf("parse frontmatter in %s: %w", path, err)
		}
		if fm.Code == "" || fm.Category == "" {
			continue
		}

		tmpl := fm.Template
		if tmpl == "" {
			tmpl = fm.Message
		}
		if tmpl == "" {
			tmpl = fm.Code
		}
		if fm.ExitCode <= 0 {
			fm.ExitCode = 1
		}

		entries = append(entries, entry{
			Code:      fm.Code,
			ConstName: constName(fm.Code),
			Category:  fm.Category,
			ExitCode:  fm.ExitCode,
			Template:  tmpl,
		})
	}

	sort.Slice(entries, func(i, j int) bool {
		return entries[i].Code < entries[j].Code
	})
	return entries, nil
}

func extractFrontMatter(content string) (string, bool) {
	const fence = "---"
	if !strings.HasPrefix(content, fence+"\n") {
		return "", false
	}

	rest := strings.TrimPrefix(content, fence+"\n")
	idx := strings.Index(rest, "\n"+fence+"\n")
	if idx < 0 {
		return "", false
	}

	return rest[:idx], true
}

func constName(code string) string {
	var b strings.Builder
	b.WriteString("Code")
	for _, r := range code {
		switch {
		case r >= 'A' && r <= 'Z':
			b.WriteRune(r)
		case r >= 'a' && r <= 'z':
			b.WriteRune(r - 32)
		case r >= '0' && r <= '9':
			b.WriteRune(r)
		}
	}
	if b.Len() == len("Code") {
		return "CodeUnknown"
	}
	return b.String()
}

func writeCatalog(output string, entries []entry) error {
	const tpl = `package errors

// Code generated by tools/gen-errors; DO NOT EDIT.
//go:generate go run ../../tools/gen-errors -input ../../docs/errors -output catalog_gen.go

const (
	CodeUnknown = "TF-CL00"
{{- range . }}
	{{ .ConstName }} = "{{ .Code }}"
{{- end }}
)

var catalog = map[string]CatalogEntry{
	CodeUnknown: {
		Code:     CodeUnknown,
		Category: string(CatCLI),
		ExitCode: 1,
		Template: "unknown application error",
	},
{{- range . }}
	{{ .ConstName }}: {
		Code:     {{ .ConstName }},
		Category: "{{ .Category }}",
		ExitCode: {{ .ExitCode }},
		Template: {{ printf "%q" .Template }},
	},
{{- end }}
}
`
	t, err := template.New("catalog").Parse(tpl)
	if err != nil {
		return fmt.Errorf("parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, entries); err != nil {
		return fmt.Errorf("execute template: %w", err)
	}

	if err := os.MkdirAll(filepath.Dir(output), 0o755); err != nil {
		return fmt.Errorf("mkdir output dir: %w", err)
	}
	if err := os.WriteFile(output, buf.Bytes(), 0o644); err != nil {
		return fmt.Errorf("write output file: %w", err)
	}
	return nil
}
