package errors

// Code generated by tools/gen-errors; DO NOT EDIT.
//go:generate go run ../../tools/gen-errors -input ../../docs/errors -output catalog_gen.go

const (
	CodeUnknown = "TF-CL00"
	CodeTFAI01 = "TF-AI01"
	CodeTFAI02 = "TF-AI02"
	CodeTFAI03 = "TF-AI03"
	CodeTFCF01 = "TF-CF01"
	CodeTFCF02 = "TF-CF02"
	CodeTFCL01 = "TF-CL01"
	CodeTFCL02 = "TF-CL02"
	CodeTFGH01 = "TF-GH01"
	CodeTFGH02 = "TF-GH02"
	CodeTFGH03 = "TF-GH03"
	CodeTFGT01 = "TF-GT01"
	CodeTFGT02 = "TF-GT02"
	CodeTFIX01 = "TF-IX01"
	CodeTFRB01 = "TF-RB01"
	CodeTFRB02 = "TF-RB02"
	CodeTFRB03 = "TF-RB03"
	CodeTFRB04 = "TF-RB04"
)

var catalog = map[string]CatalogEntry{
	CodeUnknown: {
		Code:     CodeUnknown,
		Category: string(CatCLI),
		ExitCode: 1,
		Template: "unknown application error",
	},
	CodeTFAI01: {
		Code:     CodeTFAI01,
		Category: "ai",
		ExitCode: 4,
		Template: "API key not set for provider: %s",
	},
	CodeTFAI02: {
		Code:     CodeTFAI02,
		Category: "ai",
		ExitCode: 4,
		Template: "AI API error: %s",
	},
	CodeTFAI03: {
		Code:     CodeTFAI03,
		Category: "ai",
		ExitCode: 4,
		Template: "provider configuration error: %s",
	},
	CodeTFCF01: {
		Code:     CodeTFCF01,
		Category: "config",
		ExitCode: 1,
		Template: "not a teraflow project: %s",
	},
	CodeTFCF02: {
		Code:     CodeTFCF02,
		Category: "config",
		ExitCode: 1,
		Template: "configuration file is invalid: %s",
	},
	CodeTFCL01: {
		Code:     CodeTFCL01,
		Category: "cli",
		ExitCode: 2,
		Template: "required flag %q not set",
	},
	CodeTFCL02: {
		Code:     CodeTFCL02,
		Category: "cli",
		ExitCode: 2,
		Template: "invalid argument %q for %s",
	},
	CodeTFGH01: {
		Code:     CodeTFGH01,
		Category: "github",
		ExitCode: 4,
		Template: "GitHub CLI (gh) is not installed",
	},
	CodeTFGH02: {
		Code:     CodeTFGH02,
		Category: "github",
		ExitCode: 4,
		Template: "GitHub is not authenticated",
	},
	CodeTFGH03: {
		Code:     CodeTFGH03,
		Category: "github",
		ExitCode: 4,
		Template: "GitHub API error: %s",
	},
	CodeTFGT01: {
		Code:     CodeTFGT01,
		Category: "gate",
		ExitCode: 5,
		Template: "gate conditions not met: %s",
	},
	CodeTFGT02: {
		Code:     CodeTFGT02,
		Category: "gate",
		ExitCode: 5,
		Template: "gate rule not found for process: %s",
	},
	CodeTFIX01: {
		Code:     CodeTFIX01,
		Category: "index",
		ExitCode: 1,
		Template: "index not found (run 'teraflow index build' first)",
	},
	CodeTFRB01: {
		Code:     CodeTFRB01,
		Category: "rbac",
		ExitCode: 3,
		Template: "permission denied: user %q lacks %s",
	},
	CodeTFRB02: {
		Code:     CodeTFRB02,
		Category: "rbac",
		ExitCode: 3,
		Template: "rbac enabled but current user could not be determined",
	},
	CodeTFRB03: {
		Code:     CodeTFRB03,
		Category: "rbac",
		ExitCode: 3,
		Template: "role not found: %s",
	},
	CodeTFRB04: {
		Code:     CodeTFRB04,
		Category: "rbac",
		ExitCode: 3,
		Template: "cannot remove the last admin: %s",
	},
}
