#!/usr/bin/env bash
set -euo pipefail

VERSION="${1:-}"
NOTE="${2:-fix: release automation update}"

if [[ -z "$VERSION" ]] || [[ ! "$VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "Usage: $0 <version> [note] (e.g. v0.5.8)" >&2
  exit 1
fi

if ! command -v gh >/dev/null 2>&1; then
  echo "gh CLI is required" >&2
  exit 1
fi

if ! git diff --quiet || ! git diff --cached --quiet; then
  echo "Working tree must be clean before release" >&2
  exit 1
fi

if [[ ! -f main.go ]]; then
  echo "main.go not found" >&2
  exit 1
fi

if [[ ! -f CHANGELOG.md ]]; then
  echo "CHANGELOG.md not found" >&2
  exit 1
fi

# Update main.go version variable in a portable way.
perl -0777 -i -pe "s/var version = \"v[0-9]+\.[0-9]+\.[0-9]+\"/var version = \"$VERSION\"/g" main.go

PLAIN_VERSION="${VERSION#v}"
TODAY="$(date +%F)"
if ! grep -q "^## \[$PLAIN_VERSION\]" CHANGELOG.md; then
  awk -v ver="$PLAIN_VERSION" -v today="$TODAY" -v note="$NOTE" '
    {
      print $0
      if (!inserted && $0 == "## [Unreleased]") {
        print ""
        print "## [" ver "] - " today
        print ""
        print "### Bug Fixes"
        print "- " note
        inserted = 1
      }
    }
  ' CHANGELOG.md > CHANGELOG.md.tmp && mv CHANGELOG.md.tmp CHANGELOG.md
fi

git add main.go CHANGELOG.md scripts/release.sh
git commit -m "chore: release $VERSION"

gh pr create \
  --title "chore: release $VERSION" \
  --base main \
  --body "## $VERSION

### Bug Fixes
- $NOTE

Generated by scripts/release.sh"
