package discovery

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
)

// TemplateQuestion defines one discovery question generated by LLM.
type TemplateQuestion struct {
	ID             string   `yaml:"id" json:"id"`
	Question       string   `yaml:"question" json:"question"`
	Category       string   `yaml:"category" json:"category"`
	Recommendation string   `yaml:"recommendation,omitempty" json:"recommendation,omitempty"`
	DependsOn      []string `yaml:"depends_on,omitempty" json:"depends_on,omitempty"`
}

// LLMGenerator generates initial tree seed from discussion text.
type LLMGenerator interface {
	Generate(ctx context.Context, prompt string) (string, error)
}

// TreeBuildOptions controls optional context for LLM-based tree generation.
type TreeBuildOptions struct {
	DocContext             string
	TemplateItems          []TemplateItem
	CollectedFields        []string
	UnfulfilledRequiredIDs []string
}

// BuildInitialTreeFromTemplate builds an initial branch tree from template items.
func BuildInitialTreeFromTemplate(tmpl RequirementTemplate) []Branch {
	out := make([]Branch, 0, len(tmpl.Items))
	for _, item := range tmpl.Items {
		id := strings.TrimSpace(item.ID)
		if id == "" {
			continue
		}
		question := strings.TrimSpace(item.PromptHint)
		if question == "" {
			question = strings.TrimSpace(item.Description)
		}
		if question == "" {
			question = strings.TrimSpace(item.Name)
		}
		if question == "" {
			question = id
		}

		out = append(out, Branch{
			ID:             id,
			Question:       question,
			Category:       normalizeTemplateCategory(item.Category),
			Status:         StatusPending,
			Recommendation: strings.TrimSpace(item.DefaultRecommendation),
			DependsOn:      append([]string(nil), item.DependsOn...),
		})
	}
	return out
}

// BuildInitialTree keeps backward compatibility with the old API signature.
func BuildInitialTree(tmpl DecisionTreeTemplate, _ []string) []Branch {
	return BuildInitialTreeFromTemplate(tmpl)
}

func BuildInitialTreeWithLLM(ctx context.Context, llm LLMGenerator, discussionBody string, fallback DecisionTreeTemplate, opts TreeBuildOptions) ([]Branch, error) {
	if llm == nil {
		return BuildInitialTreeFromTemplate(fallback), nil
	}

	var promptBuilder strings.Builder
	promptBuilder.WriteString("投稿内容から要件探索の決定木を生成し、JSON配列で返してください。各要素は id/question/category/recommendation/depends_on を持つこと。")
	trimmedDocContext := strings.TrimSpace(opts.DocContext)
	if trimmedDocContext != "" {
		promptBuilder.WriteString("\n\n【既存文書コンテキスト】\n")
		promptBuilder.WriteString(trimmedDocContext)
	}
	appendTemplatePromptContext(&promptBuilder, fallback, opts)
	promptBuilder.WriteString("\n\n【投稿内容】\n")
	promptBuilder.WriteString(strings.TrimSpace(discussionBody))

	prompt := promptBuilder.String()
	raw, err := llm.Generate(ctx, prompt)
	if err != nil {
		return BuildInitialTreeFromTemplate(fallback), nil
	}

	var rows []TemplateQuestion
	if err := json.Unmarshal([]byte(strings.TrimSpace(raw)), &rows); err != nil {
		return BuildInitialTreeFromTemplate(fallback), nil
	}

	out := make([]Branch, 0, len(rows))
	for _, row := range rows {
		if strings.TrimSpace(row.ID) == "" || strings.TrimSpace(row.Question) == "" {
			continue
		}
		category := normalizeTemplateCategory(row.Category)
		if strings.TrimSpace(row.Category) == "" {
			category = TemplateCategoryRecommended
		}
		out = append(out, Branch{
			ID:             strings.TrimSpace(row.ID),
			Question:       strings.TrimSpace(row.Question),
			Category:       category,
			Status:         StatusPending,
			Recommendation: strings.TrimSpace(row.Recommendation),
			DependsOn:      append([]string(nil), row.DependsOn...),
		})
	}
	if len(out) == 0 {
		return BuildInitialTreeFromTemplate(fallback), nil
	}
	return out, nil
}

func appendTemplatePromptContext(builder *strings.Builder, fallback DecisionTreeTemplate, opts TreeBuildOptions) {
	items := opts.TemplateItems
	if len(items) == 0 {
		items = fallback.Items
	}
	if len(items) > 0 {
		builder.WriteString("\n\n【要件定義書テンプレート項目】\n")
		for _, item := range items {
			id := strings.TrimSpace(item.ID)
			if id == "" {
				continue
			}
			label := strings.TrimSpace(item.Name)
			if label == "" {
				label = id
			}
			category := normalizeTemplateCategory(item.Category)
			builder.WriteString(fmt.Sprintf("- %s (%s): %s\n", label, id, category))
		}
	}
	if len(opts.CollectedFields) > 0 {
		builder.WriteString("\n【収集済み項目】\n")
		for _, id := range opts.CollectedFields {
			id = strings.TrimSpace(id)
			if id == "" {
				continue
			}
			builder.WriteString("- " + id + "\n")
		}
	}
	if len(opts.UnfulfilledRequiredIDs) > 0 {
		builder.WriteString("\n【未充足の必須項目】\n")
		for _, id := range opts.UnfulfilledRequiredIDs {
			id = strings.TrimSpace(id)
			if id == "" {
				continue
			}
			builder.WriteString("- " + id + "\n")
		}
		builder.WriteString("\n未充足の必須項目を優先的に質問してください。\n")
	}
}
